### ISSUE TITLE
Panic when running `cargo run` on unmodified repo

### ISSUE THREAD

**Issue by Fishrock123** [amethyst/evoli#114]
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.11.1
[INFO][amethyst::app] Platform: x86_64-pc-windows-msvc
[INFO][amethyst::app] Amethyst git commit: 9709f4fdddffcfef4d17f342260b4bb0e976e9b1
[INFO][amethyst::app] Rustc version: 1.44.1 Stable
[INFO][amethyst::app] Rustc git commit: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<error::BoxedErr>` uninitialized, which is invalid', C:\Users\Jeremiah\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libcore\mem\mod.rs:661:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.4.1\src\ms_queue.rs:204:20
stack backtrace:
   0:     0x7ff6deabd1ef - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1:     0x7ff6deabd1ef - std::sys_common::backtrace::_print_fmt
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff6deabd1ef - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff6dead664b - core::fmt::write
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   4:     0x7ff6deab975c - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
   5:     0x7ff6deac041c - std::sys_common::backtrace::_print
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff6deac041c - std::sys_common::backtrace::print
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff6deac041c - std::panicking::default_hook::{{closure}}
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   8:     0x7ff6deac005f - std::panicking::default_hook
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
   9:     0x7ff6deac0c07 - std::panicking::rust_panic_with_hook
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
  10:     0x7ff6deac078f - std::panicking::begin_panic_handler
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  11:     0x7ff6dead42f0 - core::panicking::panic_fmt
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
  12:     0x7ff6dead423c - core::panicking::panic
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:54
  13:     0x7ff6de974927 - core::option::Option<crossbeam::ms_queue::Node<specs::error::BoxedErr>*>::unwrap<crossbeam::ms_queue::Node<specs::error::BoxedErr>*>
                               at C:\Users\Jeremiah\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\macros\mod.rs:34
  14:     0x7ff6de96c781 - crossbeam::ms_queue::MsQueue<specs::error::BoxedErr>::pop_internal
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.4.1\src\ms_queue.rs:204
  15:     0x7ff6de96c781 - crossbeam::ms_queue::MsQueue<specs::error::BoxedErr>::try_pop<specs::error::BoxedErr>
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.4.1\src\ms_queue.rs:249
  16:     0x7ff6de96b039 - crossbeam::ms_queue::{{impl}}::drop<specs::error::BoxedErr>
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.4.1\src\ms_queue.rs:332
  17:     0x7ff6de9603fe - core::ptr::drop_in_place<crossbeam::ms_queue::MsQueue<specs::error::BoxedErr>>
                               at C:\Users\Jeremiah\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ptr\mod.rs:177
  18:     0x7ff6de96bb47 - crossbeam::ms_queue::MsQueue<specs::error::BoxedErr>::new<specs::error::BoxedErr>
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.4.1\src\ms_queue.rs:79
  19:     0x7ffa0cbf1030 - <unknown>
  20:     0x7ffa0cbf35d6 - is_exception_typeof
  21:     0x7ffa0cbfbb64 - _C_specific_handler
  22:     0x7ffa0cbf3029 - is_exception_typeof
  23:     0x7ffa0cbfc021 - _CxxFrameHandler3
  24:     0x7ffa253e124f - _chkstk
  25:     0x7ffa2535d9b2 - RtlUnwindEx
  26:     0x7ffa0cbfbe89 - _C_specific_handler
  27:     0x7ffa0cbf26a9 - is_exception_typeof
  28:     0x7ffa0cbf2a05 - is_exception_typeof
  29:     0x7ffa0cbf312f - is_exception_typeof
  30:     0x7ffa0cbfc021 - _CxxFrameHandler3
  31:     0x7ffa253e11cf - _chkstk
  32:     0x7ffa253aa209 - RtlRaiseException
  33:     0x7ffa253a9fc3 - RtlRaiseException
  34:     0x7ffa2230a799 - RaiseException
  35:     0x7ffa0cbf4890 - CxxThrowException
  36:     0x7ff6deac57a1 - panic_unwind::real_imp::panic
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libpanic_unwind\seh.rs:316
  37:     0x7ff6deac5729 - panic_unwind::__rust_start_panic
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libpanic_unwind\lib.rs:96
  38:     0x7ff6deac0df8 - std::panicking::rust_panic
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:563
  39:     0x7ff6deac0cc1 - std::panicking::rust_panic_with_hook
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:533
  40:     0x7ff6deac078f - std::panicking::begin_panic_handler
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  41:     0x7ff6dead42f0 - core::panicking::panic_fmt
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
  42:     0x7ff6dead423c - core::panicking::panic
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:54
  43:     0x7ff6de96b919 - core::mem::uninitialized
                               at C:\Users\Jeremiah\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\mem\mod.rs:661
  44:     0x7ff6de96b919 - crossbeam::ms_queue::MsQueue<specs::error::BoxedErr>::new<specs::error::BoxedErr>
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.4.1\src\ms_queue.rs:71
  45:     0x7ff6de97807e - specs::common::Errors::new
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\specs-0.14.3\src\common.rs:71
  46:     0x7ff6de978041 - specs::common::{{impl}}::default
                               at C:\Users\Jeremiah\.cargo\registry\src\github.com-1ecc6299db9ec823\specs-0.14.3\src\common.rs:63
  47:     0x7ff6dd3e749e - amethyst::app::ApplicationBuilder<evolution_island::states::loading::LoadingState, amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>, amethyst::state_event::StateEventReader<amethyst_input::bindings
                               at C:\Users\Jeremiah\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\9709f4f\src\app.rs:540
  48:     0x7ff6dd3e61f0 - amethyst::app::CoreApplication<amethyst::game_data::GameData, amethyst::state_event::StateEvent<amethyst_input::bindings::StringBindings>, amethyst::state_event::StateEventReader<amethyst_input::bindings::StringBindings>>::build<amethyst::game_data::GameD
                               at C:\Users\Jeremiah\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\9709f4f\src\app.rs:208
  49:     0x7ff6ddc3f622 - evolution_island::main
                               at W:\Rust-Projects\evoli\src\main.rs:100
  50:     0x7ff6ddc2dddb - std::rt::lang_start::{{closure}}<core::result::Result<(), amethyst_error::Error>>
                               at C:\Users\Jeremiah\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  51:     0x7ff6deac0f2a - std::rt::lang_start_internal::{{closure}}
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:52
  52:     0x7ff6deac0f2a - std::panicking::try::do_call
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:331
  53:     0x7ff6deac0f2a - std::panicking::try
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:274
  54:     0x7ff6deac0f2a - std::panic::catch_unwind
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panic.rs:394
  55:     0x7ff6deac0f2a - std::rt::lang_start_internal
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
  56:     0x7ff6ddc2ddb3 - std::rt::lang_start<core::result::Result<(), amethyst_error::Error>>
                               at C:\Users\Jeremiah\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  57:     0x7ff6ddc3ffe0 - main
  58:     0x7ff6deaee5b0 - invoke_main
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  59:     0x7ff6deaee5b0 - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  60:     0x7ffa23d27bd4 - BaseThreadInitThunk
  61:     0x7ffa253ace51 - RtlUserThreadStart
```

Rust:
```
active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.44.1 (c7087fe00 2020-06-17)
```

More info:
- Windows 10 version 1903.

Let me know if there is any other helpful info I can provide.

**Comment by ashneverdawn** [comment]
This has been fixed
